JDK_HOME=c:\jdk1.4
SRC_HOME=C:\SRC\UBT\XMLFoundation\Examples\Java\ExXMLObjects
CLASSPATH=.;..;%CLASSPATH%
LIB=C:\PROGRA~1\MICROS~2\VC98\MFC\LIB;C:\PROGRA~1\MICROS~2\VC98\LIB



!IF "$(CFG)" == ""
CFG=JavaXMLFoundation - Win32 Debug
!MESSAGE No configuration specified. Defaulting to JavaXMLFoundation - Win32 Debug.
!ENDIF 

!IF "$(CFG)" != "JavaXMLFoundation - Win32 Release" && "$(CFG)" !=\
 "JavaXMLFoundation - Win32 Debug"
!MESSAGE Invalid configuration "$(CFG)" specified.
!MESSAGE You can specify a configuration when running NMAKE
!MESSAGE by defining the macro CFG on the command line. For example:
!MESSAGE 
!MESSAGE NMAKE /f "JavaXMLFoundation.mak" CFG="JavaXMLFoundation - Win32 Debug"
!MESSAGE 
!MESSAGE Possible choices for configuration are:
!MESSAGE 
!MESSAGE "JavaXMLFoundation - Win32 Release" (based on\
 "Win32 (x86) Dynamic-Link Library")
!MESSAGE "JavaXMLFoundation - Win32 Debug" (based on\
 "Win32 (x86) Dynamic-Link Library")
!MESSAGE 
!ERROR An invalid configuration is specified.
!ENDIF 

!IF "$(OS)" == "Windows_NT"
NULL=
!ELSE 
NULL=nul
!ENDIF 

CPP=cl.exe
MTL=midl.exe
RSC=rc.exe

!IF  "$(CFG)" == "JavaXMLFoundation - Win32 Release"

OUTDIR=.\Release
INTDIR=.\Release
# Begin Custom Macros
OutDir=.\Release
# End Custom Macros

!IF "$(RECURSE)" == "0" 

ALL : "JavaXMLFoundation.dll"

!ELSE 

ALL : "JavaXMLFoundation.dll"

!ENDIF 

CLEAN :
	-@erase "$(INTDIR)\JavaFoundation.obj"
	-@erase "$(INTDIR)\vc50.idb"
	-@erase "$(INTDIR)\JavaXMLFoundation.pch"
	-@erase "$(OUTDIR)\JavaXMLFoundation.dll"
	-@erase "$(OUTDIR)\JavaXMLFoundation.exp"
	-@erase "$(OUTDIR)\JavaXMLFoundation.lib"

"$(OUTDIR)" :
    if not exist "$(OUTDIR)/$(NULL)" mkdir "$(OUTDIR)"

CPP_PROJ=/nologo /MT /W3 /GX /O2 /D "WIN32" /D "NDEBUG" /D "_WINDOWS"\
 /Fp"$(INTDIR)\JavaXMLFoundation.pch" /YX /Fo"$(INTDIR)\\" /Fd"$(INTDIR)\\" /FD /c 
CPP_OBJS=.\Release/
CPP_SBRS=.
MTL_PROJ=/nologo /D "NDEBUG" /mktyplib203 /o NUL /win32 
BSC32=bscmake.exe
BSC32_FLAGS=/nologo /o"JavaXMLFoundation.bsc" 
BSC32_SBRS= \
	
LINK32=link.exe
LINK32_FLAGS=/libpath:$(LIB) ../../Library/Build/ReleaseClient/XMLFoundationClient.lib kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib\
 advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib\
 odbccp32.lib /nologo /subsystem:windows /dll /incremental:no\
 /pdb:"JavaXMLFoundation.pdb" /machine:I386\
 /out:"JavaXMLFoundation.dll" /implib:"JavaXMLFoundation.lib" 
LINK32_OBJS= \
	"$(INTDIR)\JavaFoundation.obj"

"JavaXMLFoundation.dll" : "$(OUTDIR)" $(DEF_FILE) $(LINK32_OBJS)
    $(LINK32) @<<
  $(LINK32_FLAGS) $(LINK32_OBJS)
<<

!ELSEIF  "$(CFG)" == "JavaXMLFoundation - Win32 Debug"

OUTDIR=.\Debug
INTDIR=.\Debug

!IF "$(RECURSE)" == "0" 

ALL : "JavaXMLFoundation.dll"

!ELSE 

ALL : "JavaXMLFoundation.dll"

!ENDIF 

CLEAN :
	-@erase "$JavaXMLFoundation.pch"
	-@erase "$JavaXMLFoundation.exp"
	-@erase "JavaXMLFoundation.lib"
	-@erase "JavaXMLFoundation.pdb"
	-@erase "JavaXMLFoundation.dll"
	-@erase "JavaXMLFoundation.ilk"

"$(OUTDIR)" :
    if not exist "$(OUTDIR)/$(NULL)" mkdir "$(OUTDIR)"

CPP_PROJ=/nologo /MTd /W3 /Gm /GX /Zi /Od /I../../Library/inc /I "$(JDK_HOME)\include" /I\
 "$(JDK_HOME)\include\win32" /D "WIN32" /D "_DEBUG" /D "_WINDOWS"\
 /Fp"$(INTDIR)\JavaXMLFoundation.pch" /YX /Fo"$(INTDIR)\\" /Fd"$(INTDIR)\\" /FD /c 
CPP_OBJS=.\Debug/
CPP_SBRS=.
MTL_PROJ=/nologo /D "_DEBUG" /mktyplib203 /o NUL /win32 
BSC32=bscmake.exe
BSC32_FLAGS=/nologo /o"$(OUTDIR)\JavaXMLFoundation.bsc" 
BSC32_SBRS= \
	
LINK32=link.exe
LINK32_FLAGS=/libpath:$(LIB) ../../Library/Build/ReleaseClient/XMLFoundationClient.lib kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib\
 advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib\
 odbccp32.lib /nologo /subsystem:windows /dll /incremental:yes\
 /pdb:"$(OUTDIR)\JavaXMLFoundation.pdb" /debug /machine:I386\
 /out:"JavaXMLFoundation.dll"\
 /implib:"JavaXMLFoundation.lib" /pdbtype:sept
LINK32_OBJS= \
	"$(INTDIR)\JavaFoundation.obj"

"JavaXMLFoundation.dll" : "$(OUTDIR)" $(DEF_FILE)\
 $(LINK32_OBJS)
    $(LINK32) @<<
  $(LINK32_FLAGS) $(LINK32_OBJS)
<<

!ENDIF 

.c{$(CPP_OBJS)}.obj::
   $(CPP) @<<
   $(CPP_PROJ) $< 
<<

.cpp{$(CPP_OBJS)}.obj::
   $(CPP) @<<
   $(CPP_PROJ) $< 
<<

.cxx{$(CPP_OBJS)}.obj::
   $(CPP) @<<
   $(CPP_PROJ) $< 
<<

.c{$(CPP_SBRS)}.sbr::
   $(CPP) @<<
   $(CPP_PROJ) $< 
<<

.cpp{$(CPP_SBRS)}.sbr::
   $(CPP) @<<
   $(CPP_PROJ) $< 
<<

.cxx{$(CPP_SBRS)}.sbr::
   $(CPP) @<<
   $(CPP_PROJ) $< 
<<


!IF "$(CFG)" == "JavaXMLFoundation - Win32 Release" || "$(CFG)" ==\
 "JavaXMLFoundation - Win32 Debug"
SOURCE=JavaFoundation.cpp

!IF  "$(CFG)" == "JavaXMLFoundation - Win32 Release"

DEP_CPP_JNIAL=\
	"JavaFoundation.h"\
	

"$(INTDIR)\jniAllocObjectEx.obj" : $(SOURCE) $(DEP_CPP_JNIAL) "$(INTDIR)"
	$(CPP) $(CPP_PROJ) $(SOURCE)


!ELSEIF  "$(CFG)" == "JavaXMLFoundation - Win32 Debug"

DEP_CPP_JNIAL=\
	"$(JDK_HOME)\include\jni.h"\
	"$(JDK_HOME)\include\win32\jni_md.h"\
	"jniXMLObject.h"\
	

"$(INTDIR)\JavaFoundation.obj" : $(SOURCE) $(DEP_CPP_JNIAL) "$(INTDIR)"
	$(CPP) $(CPP_PROJ) $(SOURCE)


!ENDIF 


!ENDIF 

