CC = g++
CPPFLAGS = -w -c -D_INTEL -D___LINUX -D___LINUX64  -I../../Libraries/XMLFoundation/inc
COPY = cp

TransactXML: \
	clear \
	CustomHTTPServiceConsole.o 
	 
	$(CC) \
		-o CustomHTTPServiceConsole \
		-L../../Libraries/XMLFoundation/Build \
		CustomHTTPServiceConsole.o \
		-lpthread -ldl -lXMLFoundation

CustomHTTPServiceConsole.o: ./CustomHTTPServiceConsole.cpp
	$(CC) $(CPPFLAGS) ./CustomHTTPServiceConsole.cpp -o ./CustomHTTPServiceConsole.o


clear:
	clear

