CC = g++
CPPFLAGS = -w -c -D_INTEL -D___LINUX  -D___LINUX64 -I../../../Libraries/XMLFoundation/inc -I/home/user/perl-5.38.0
COPY = cp

TransactXML: \
	clear \
	PerlTest.o 
	 
	$(CC) \
		-o PerlTest \
		-L../../../Libraries/XMLFoundation/Build \
		-L/home/user/perl-5.38.0 \
		PerlTest.o \
		-lperl -lcrypt -lpthread -ldl -lXMLFoundation 

PerlTest.o: ./PerlTest.cpp
	$(CC) $(CPPFLAGS) ./PerlTest.cpp -o ./PerlTest.o


clear:
	clear

