/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_server_app_Server */

#ifndef _Included_com_server_app_Server
#define _Included_com_server_app_Server
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_server_app_Server
 * Method:    serverInteract
 * Signature: (ILjava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_server_app_Server_serverInteract
  (JNIEnv *, jobject, jint, jstring, jstring);

/*
 * Class:     com_server_app_Server
 * Method:    serverStart
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_server_app_Server_serverStart
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
